import React, { useState, useEffect, useCallback } from 'react';
import { 
  Box, 
  Button, 
  Typography, 
  LinearProgress, 
  Alert, 
  Card, 
  CardContent,
  List,
  ListItem,
  ListItemText,
  Divider,
  CircularProgress,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Switch,
  FormControlLabel,
  IconButton,
  Tooltip
} from '@mui/material';
import { 
  PowerSettingsNew as PowerIcon,
  Settings as SettingsIcon,
  Add as AddIcon,
  Delete as DeleteIcon,
  Wifi as WifiIcon,
  WifiOff as WifiOffIcon
} from '@mui/icons-material';

// 定义接口
interface Portal {
  id: string;
  name: string;
  url: string;
  username?: string;
  isDefault: boolean;
}

interface VpnStatus {
  type: 'Disconnected' | 'Connecting' | 'Connected' | 'Disconnecting';
  portal?: string;
  gateway?: string;
}

// Tauri invoke函数声明
declare global {
  interface Window {
    __TAURI__: any;
  }
}

const invoke = window.__TAURI__.invoke;

const GlobalProtectGUI: React.FC = () => {
  const [vpnStatus, setVpnStatus] = useState<VpnStatus>({ type: 'Disconnected' });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [portals, setPortals] = useState<Portal[]>([]);
  const [selectedPortal, setSelectedPortal] = useState<string>('');
  const [autoConnect, setAutoConnect] = useState(false);
  const [showAddPortal, setShowAddPortal] = useState(false);
  const [newPortalName, setNewPortalName] = useState('');
  const [newPortalUrl, setNewPortalUrl] = useState('');

  // 加载门户列表
  const loadPortals = useCallback(async () => {
    try {
      const loadedPortals: Portal[] = await invoke('get_portals');
      setPortals(loadedPortals);
      if (loadedPortals.length > 0) {
        setSelectedPortal(loadedPortals[0].id);
      }
    } catch (err: any) {
      console.error('Failed to load portals:', err);
      setError('Failed to load portal list');
    }
  }, []);

  // 加载当前状态
  const loadCurrentStatus = useCallback(async () => {
    try {
      const status: VpnStatus = await invoke('get_current_status');
      setVpnStatus(status);
    } catch (err: any) {
      console.error('Failed to load current status:', err);
    }
  }, []);

  // 连接VPN
  const handleConnect = async () => {
    if (!selectedPortal) {
      setError('Please select a portal');
      return;
    }
    
    const portal = portals.find(p => p.id === selectedPortal);
    if (!portal) {
      setError('Selected portal not found');
      return;
    }
    
    setLoading(true);
    setError(null);
    
    try {
      await invoke('connect_vpn', { 
        portalUrl: portal.url,
        gatewayAddress: undefined 
      });
      await loadCurrentStatus();
    } catch (err: any) {
      setError(err);
      setLoading(false);
    }
  };

  // 断开VPN
  const handleDisconnect = async () => {
    setLoading(true);
    setError(null);
    
    try {
      await invoke('disconnect_vpn');
      await loadCurrentStatus();
    } catch (err: any) {
      setError(err);
      setLoading(false);
    }
  };

  // 添加门户
  const handleAddPortal = async () => {
    if (!newPortalName.trim() || !newPortalUrl.trim()) {
      setError('Portal name and URL are required');
      return;
    }
    
    try {
      const portal: Portal = {
        id: '', // Will be generated by backend
        name: newPortalName.trim(),
        url: newPortalUrl.trim(),
        isDefault: false
      };
      
      await invoke('add_portal', { portal });
      setNewPortalName('');
      setNewPortalUrl('');
      setShowAddPortal(false);
      await loadPortals();
    } catch (err: any) {
      setError(err);
    }
  };

  // 删除门户
  const handleRemovePortal = async (portalId: string) => {
    try {
      await invoke('remove_portal', { portalId });
      await loadPortals();
    } catch (err: any) {
      setError(err);
    }
  };

  // 切换自动连接
  const handleAutoConnectToggle = async (enabled: boolean) => {
    try {
      if (enabled) {
        await invoke('enable_auto_connect');
      } else {
        await invoke('disable_auto_connect');
      }
      setAutoConnect(enabled);
    } catch (err: any) {
      setError(err);
    }
  };

  // 初始化
  useEffect(() => {
    loadPortals();
    loadCurrentStatus();
    
    // 设置自动连接状态（需要从配置加载）
    // TODO: 实现自动连接状态加载
  }, [loadPortals, loadCurrentStatus]);

  const isConnected = vpnStatus.type === 'Connected';
  const isConnecting = vpnStatus.type === 'Connecting';
  const isDisconnecting = vpnStatus.type === 'Disconnecting';

  const renderStatusIcon = () => {
    if (isConnected) {
      return <WifiIcon color="success" />;
    } else if (isConnecting || isDisconnecting) {
      return <CircularProgress size={24} />;
    } else {
      return <WifiOffIcon color="error" />;
    }
  };

  const renderStatusText = () => {
    switch (vpnStatus.type) {
      case 'Disconnected':
        return 'Disconnected';
      case 'Connecting':
        return 'Connecting...';
      case 'Connected':
        return `Connected to ${vpnStatus.portal || 'Unknown'}`;
      case 'Disconnecting':
        return 'Disconnecting...';
      default:
        return 'Unknown';
    }
  };

  return (
    <Box sx={{ p: 3, maxWidth: 800, mx: 'auto' }}>
      <Card>
        <CardContent>
          <Box display="flex" alignItems="center" justifyContent="space-between" mb={3}>
            <Typography variant="h4" component="h1">
              GlobalProtect VPN Client
            </Typography>
            <Tooltip title="Settings">
              <IconButton onClick={() => invoke('open_settings')}>
                <SettingsIcon />
              </IconButton>
            </Tooltip>
          </Box>
          
          <Divider sx={{ my: 2 }} />
          
          {/* Status Section */}
          <Box display="flex" alignItems="center" gap={2} mb={3}>
            {renderStatusIcon()}
            <Typography variant="h6">{renderStatusText()}</Typography>
          </Box>

          {/* Progress Indicator */}
          {(isConnecting || isDisconnecting) && (
            <Box mb={2}>
              <LinearProgress />
            </Box>
          )}

          {/* Action Buttons */}
          <Box display="flex" gap={2} justifyContent="center" mb={3}>
            {!isConnected ? (
              <Button
                variant="contained"
                color="primary"
                startIcon={<PowerIcon />}
                onClick={handleConnect}
                disabled={isConnecting || !selectedPortal}
              >
                Connect
              </Button>
            ) : (
              <Button
                variant="contained"
                color="secondary"
                startIcon={<PowerIcon />}
                onClick={handleDisconnect}
                disabled={isDisconnecting}
              >
                Disconnect
              </Button>
            )}
          </Box>

          {/* Portal Selection */}
          <Box mb={3}>
            <FormControl fullWidth>
              <InputLabel>Portal</InputLabel>
              <Select
                value={selectedPortal}
                label="Portal"
                onChange={(e) => setSelectedPortal(e.target.value as string)}
                disabled={isConnected || isConnecting || isDisconnecting}
              >
                {portals.map((portal) => (
                  <MenuItem key={portal.id} value={portal.id}>
                    {portal.name} ({portal.url})
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
            
            {/* Add Portal Button */}
            <Box mt={1}>
              <Button
                variant="outlined"
                size="small"
                startIcon={<AddIcon />}
                onClick={() => setShowAddPortal(!showAddPortal)}
                disabled={isConnected || isConnecting || isDisconnecting}
              >
                {showAddPortal ? 'Cancel' : 'Add Portal'}
              </Button>
            </Box>
          </Box>

          {/* Add Portal Form */}
          {showAddPortal && (
            <Box mb={3} p={2} border={1} borderColor="divider" borderRadius={1}>
              <Typography variant="subtitle1" mb={2}>Add New Portal</Typography>
              <TextField
                fullWidth
                label="Portal Name"
                value={newPortalName}
                onChange={(e) => setNewPortalName(e.target.value)}
                margin="normal"
              />
              <TextField
                fullWidth
                label="Portal URL"
                placeholder="https://vpn.example.com"
                value={newPortalUrl}
                onChange={(e) => setNewPortalUrl(e.target.value)}
                margin="normal"
              />
              <Box display="flex" gap={1} mt={2}>
                <Button
                  variant="contained"
                  color="primary"
                  onClick={handleAddPortal}
                >
                  Add Portal
                </Button>
                <Button
                  variant="outlined"
                  onClick={() => setShowAddPortal(false)}
                >
                  Cancel
                </Button>
              </Box>
            </Box>
          )}

          {/* Portal List with Delete */}
          {portals.length > 0 && (
            <Box mb={3}>
              <Typography variant="subtitle1" mb={1}>Configured Portals</Typography>
              <List dense>
                {portals.map((portal) => (
                  <ListItem
                    key={portal.id}
                    secondaryAction={
                      portals.length > 1 && (
                        <IconButton
                          edge="end"
                          onClick={() => handleRemovePortal(portal.id)}
                          disabled={isConnected || isConnecting || isDisconnecting}
                        >
                          <DeleteIcon />
                        </IconButton>
                      )
                    }
                  >
                    <ListItemText
                      primary={portal.name}
                      secondary={portal.url}
                    />
                  </ListItem>
                ))}
              </List>
            </Box>
          )}

          {/* Auto Connect Toggle */}
          <Box mb={3}>
            <FormControlLabel
              control={
                <Switch
                  checked={autoConnect}
                  onChange={(e) => handleAutoConnectToggle(e.target.checked)}
                  disabled={isConnecting || isDisconnecting}
                />
              }
              label="Auto-connect on startup"
            />
          </Box>

          {/* Error Alert */}
          {error && (
            <Alert 
              severity="error" 
              onClose={() => setError(null)} 
              sx={{ mt: 2 }}
            >
              {error}
            </Alert>
          )}

          {/* Connection Info */}
          {isConnected && vpnStatus.gateway && (
            <Box mt={3} p={2} bgcolor="#f5f5f5" borderRadius={1}>
              <Typography variant="subtitle2" gutterBottom>Connection Details:</Typography>
              <List dense>
                <ListItem>
                  <ListItemText 
                    primary="Portal" 
                    secondary={vpnStatus.portal} 
                  />
                </ListItem>
                <ListItem>
                  <ListItemText 
                    primary="Gateway" 
                    secondary={vpnStatus.gateway} 
                  />
                </ListItem>
              </List>
            </Box>
          )}
        </CardContent>
      </Card>
    </Box>
  );
};

export default GlobalProtectGUI;